### PR TITLE
Add support for the ROS build system

### PR DESCRIPTION
**Pull request by Timple**
This allows all ROS packages to include this wonderful library by listing this github repository as a dependency.

### CODE REVIEW

**Comment by Neargye** [comment]
Add notice to readme too.

**Comment by Timple** [comment]
Marking as draft as I found a possible improvement.

**Comment by Timple** [comment]
Works for ROS1.
ROS2 pending...

**Comment by Timple** [comment]
ROS2 operational. Required an extra `target_link_libraries` step.

**Comment by Neargye** [comment]
@Timple is it ready?

**Comment by Timple** [comment]
Yes, verified on both ROS versions

Sorry for the iterations, I thought I was there on the first commit 🙂

**Comment by Neargye** [comment]
Many iterations are ok.
thanks for pr!

**Comment by Timple** [comment]
Thank you!

Would you mind if I release it to the ROS package manager as well?
Source and documentation will keep pointing to this repository.

**Comment by Neargye** [comment]
I am for any improvement for the community.

As I understand, I need to update every release package.xml?

**Comment by Timple** [comment]
Yes, keeping the versions in sync would be ideal! Similar to meson.build I guess...

Unfortunately the XML structure cannot parse git tags...

**Comment by Neargye** [comment]
@Timple is it possible remove me from mailing in build system ros?

**Comment by Timple** [comment]
Ow, I'm not sure how you auto-subscribed (and I did not). 

Seems to be because of the `<maintainer` taq in the `package.xml` file.

Shall I list myself as ROS maintainer as I'm updating the ROS buildfarm? 
I would list you as author, to give credit where it's due. Being an author does not auto-subscribe to the buildfarm mailings.

**Comment by tdenewiler** [comment]
I was able to quickly add this to a ROS 2-based node I am developing. It's great! Thanks for the library and for the ROS integration.

One thing that would make this better is if I could resolve names of constants in ROS messages. In ROS a message is defined in a file like this:

```
int8 NAME_A = 0
int8 NAME_B = 1

int8 data
```

The ROS build system creates auto-generated C++ header files. The relevant contents look like this:

```
// constant declarations
  static constexpr int8_t NAME_A =
    0;
  static constexpr int8_t NAME_B =
    1;
// constant definitions
#if __cplusplus < 201703L
// static constexpr member variable definitions are only needed in C++14 and below, deprecated in C++17
template<typename ContainerAllocator>
constexpr int8_t NAME_A_<ContainerAllocator>::CONTINGENCY;
#endif  // __cplusplus < 201703L
#if __cplusplus < 201703L
// static constexpr member variable definitions are only needed in C++14 and below, deprecated in C++17
template<typename ContainerAllocator>
constexpr int8_t NAME_B_<ContainerAllocator>::CONTINGENCY;
#endif  // __cplusplus < 201703L
```

Do either of you know if I can use this library to resolve the names of the constants from values in this context?

**Pull request merged**
