### PR TITLE
enum_map class

### PR DESCRIPTION
**Pull request by jlwoolf**
I thought this could be a potential branch for the magic_enum library. It is a simple map data structure that utilizes some of the magic_enum functions to map every enum entry to a unique value.

### CODE REVIEW

**Comment by Neargye** [comment]
For updating, I didn't forget about this PR, now I'm preparing a new release `0.8.0`, and this PR will be included in the next release `0.8.1`

**Comment by schaumb** [comment]
This can be made constexpr, like I suggest [here](https://github.com/Neargye/magic_enum/issues/150)

So I think this needs an upgrade

**Comment by Neargye** [comment]
it is better to keep this class in a separate header.
And I thing need all map-api `begin/end` `find` etc, https://github.com/Neargye/magic_enum/issues/150 was just a concept idea and not advice for implementation

**Comment by florianbecker** [comment]
@jlwoolf @schaumb 
Can i help with that pr to make it mergeable for Neargye?

**Comment by jlwoolf** [comment]
@florianbecker 
I haven't really had the time to work on this much, so if you'd like to continue it, by all means go ahead. I can close this pull request if you'd like to open another with the improvements/fixes, or add you as a contributor to the fork.

**Comment by schaumb** [comment]
Hi!

I started an another [PR](https://github.com/Neargye/magic_enum/pull/187).
I implemented already `array` `bitset` `set` and `flat_set` to namespace `magic_enum::containers`.

I thought I has time to implement the `multiset` `map` and `flat_map` too.

The `array` class is semantically equal to this PR.

**Comment by Neargye** [comment]
will closed in https://github.com/Neargye/magic_enum/pull/187

**Pull request closed without merging**
