### PR TITLE
remove std:: from optionals to enable again MAGIC_ENUM_USING_ALIAS_OPTIONAL 

### PR DESCRIPTION
**Pull request by schaumb**
https://github.com/Neargye/magic_enum/issues/147

### CODE REVIEW

**Comment by Neargye** [comment]
`return std::nullopt;` -> `return {};`

**Review by Neargye — APPROVED** [review]

**Comment by Neargye** [comment]
thanks

**Comment by schaumb** [comment]
@Neargye Does it need a test?

```
template<typename T>
struct MyOpt {
    constexpr MyOpt() : mHasValue{} {}
    constexpr MyOpt(const T& v) : mHasValue{true}, val{v} { }
    constexpr bool has_value() const noexcept { return mHasValue; }
    constexpr const T& value() const noexcept { return val; }
    bool mHasValue;
    T val;
};

#define MAGIC_ENUM_USING_ALIAS_OPTIONAL template<typename T> using optional = ::MyOpt<T>;

...
```

**Comment by Neargye** [comment]
@schaumb I would create a separate test for this(and issues for tracking)

**Pull request merged**
