### PR TITLE
Simplier change only one enum instance name

### PR DESCRIPTION
**Pull request by schaumb**
If someone needs to change only one enum instance name, it is much easier with this modification.

With this, it is not necessary to write a function but enough a constant variable.

So
```
template <>
constexpr std::string_view magic_enum::customize::enum_name<Color>(Color value) noexcept {
  switch (value) {
    case Color::RED:
      return "red";
    default:
      return {};
  }
}
```

can be simplified to
```
template<>
constexpr std::string_view magic_enum::customize::enum_name_v<Color, Color::RED> = "red";
```

--- 

reorder `enum_name_v`, move to `customize::` + add test

### CODE REVIEW

**Comment by schaumb** [comment]
It seems [Visual Studio 2017](https://github.com/Neargye/magic_enum/runs/5248790375?check_suite_focus=true) does not support this "feature".

**Comment by Neargye** [comment]
I will check vs2017 locally.

**Comment by Neargye** [comment]
Wouldn't just a shorter entry work
```cpp
template <>
constexpr std::string_view magic_enum::customize::enum_name<Color>(Color value) noexcept {
  return value == Color::RED ? "red" : {};
}
```
I'm a bit concerned about creating two different customization points that might conflict, for example.

**Comment by schaumb** [comment]
This customization point enables to "cancel" an enum value.
So:
```
enum class A {
    _1,
    _1_5, 
    _2, 
    _3
};

template<>
constexpr std::string_view magic_enum::customize::enum_name_v<A, A::_1_5> = "";

static_assert(magic_enum::enum_count<A>() == 3);
```

I think it can be change to not needed to add type:
```
template<>
constexpr std::string_view magic_enum::customize::enum_name_v<A::_1_5> = "";
```

**Comment by Neargye** [comment]
to enables/disables, I would add another function like 

```cpp
template <>
constexpr std::string_view magic_enum::customize::enum_valid<Color>(Color value) noexcept {
  return value == Color::RED ? false : true;
}
```

perhaps it will be more readable.

**Comment by Neargye** [comment]
I don’t have time to watch pr yet because of the need for relocation from Kyiv.

**Comment by schaumb** [comment]
VS 2017 cannot enable to write namespace constexpr variable specialization, so:
```
template<>
constexpr std::string_view magic_enum::customize::enum_name_v<Color, Color::RED> = "red";
``` 
I need to replace to (only because VS2017)
```
namespace magic_enum::customize {
template<>
constexpr std::string_view enum_name_v<Color, Color::RED> = "red";
}
```

I wrote another test for the "canceling". ~~This fails because~~

~~`enum_name_v<Binary, Binary::ONE>` overrides somehow `enum_name_v<MaxUsedAsInvalid, MaxUsedAsInvalid::ONE>` default value (again: only for VS2017)~~

I manage it, no other VS2017 issue

**Comment by schaumb** [comment]
So I added a new test for enum value injection.
This technique enables the following:

```
enum class Numbers : int { one = 1, two, three };
constexpr auto NumberFour = static_cast<Numbers>(4);

template<>
constexpr std::string_view magic_enum::customize::enum_name_v<NumberFour> = "four";

static_assert(enum_count<Numbers>() == 4);
```

**Comment by schaumb** [comment]
https://github.com/Neargye/magic_enum/pull/166 will be awsome instead of this

**Pull request closed without merging**
